---

- name: Installing packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-setuptools

- name: Installing dependencies
  easy_install:
    name: "{{ docker_compose_pip_version }}"

- name: Installing docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present
